version: "3.1"

services:
  node:
    user: "${UID}:${GID}"
    image: fog-node:0.1
    build:
      context: .
    ports:
      - "8000:8000/tcp"
      - "8000:8000/udp"
    working_dir: "/home/python/app"
    volumes:
      - ".:/home/python/app"
